# -*- coding: utf-8 -*-
"""Content entries: helpers plus import/export (Python dicts, CSV)."""

import ast
import csv
import json
import re

from .config import CATEGORY_ALIASES, LANG_ALIASES, LANG_KEYS, LANGUAGES


def slugify(value):
    """Lower-case, underscores only - firmware-safe names (no spaces)."""
    value = str(value).strip().lower()
    value = re.sub(r"[\s\-]+", "_", value)
    value = re.sub(r"[^a-z0-9_]", "", value)
    return re.sub(r"_+", "_", value).strip("_")


def normalize_category(name):
    slug = slugify(name)
    return CATEGORY_ALIASES.get(slug, slug)


def new_entry(category, item_id, english=""):
    entry = {"category": category, "id": item_id, "reviewed": False}
    for lang in LANG_KEYS:
        entry[lang] = ""
    entry["english"] = english
    return entry


def natural_key(text):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", str(text))]


def entry_status(entry):
    """Returns (text, tag) describing translation completeness."""
    missing = [l for l in LANG_KEYS if not entry.get(l, "").strip()]
    if missing:
        return "✗ incomplete", "missing"
    if not entry.get("reviewed"):
        return "⚠ needs review", "review"
    return "✔ reviewed", "ok"


def entries_to_content(entries):
    """List of entries -> {category: {id: {language: text, ...}}} (the dict layout)."""
    content = {}
    for e in entries:
        record = {lang: e.get(lang, "") for lang in LANG_KEYS}
        record["reviewed"] = bool(e.get("reviewed"))
        content.setdefault(e["category"], {})[e["id"]] = record
    return content


def content_to_entries(content):
    entries = []
    for category, items in content.items():
        if not isinstance(items, dict):
            continue
        cat = normalize_category(category)
        for item_id, record in items.items():
            entry = new_entry(cat, slugify(item_id))
            if isinstance(record, str):
                entry["english"] = record
            elif isinstance(record, dict):
                for key, text in record.items():
                    lang = LANG_ALIASES.get(str(key).lower(), str(key).lower())
                    if lang in LANGUAGES and isinstance(text, str):
                        entry[lang] = text
                entry["reviewed"] = bool(record.get("reviewed", False))
            if entry["id"]:
                entries.append(entry)
    return entries


def merge_entries(existing, incoming):
    """Merge by (category, id); non-empty incoming text overwrites. Returns (added, updated)."""
    index = {(e["category"], e["id"]): e for e in existing}
    added = updated = 0
    for inc in incoming:
        key = (inc["category"], inc["id"])
        if key in index:
            cur = index[key]
            changed = False
            for lang in LANG_KEYS:
                if inc.get(lang, "").strip() and inc[lang] != cur.get(lang):
                    cur[lang] = inc[lang]
                    changed = True
            if inc.get("reviewed"):
                cur["reviewed"] = True
            updated += changed
        else:
            existing.append(inc)
            index[key] = inc
            added += 1
    return added, updated


def load_python_dicts(path):
    """Safely read `questions = {...}` style dictionaries from a .py file (no code runs)."""
    with open(path, "r", encoding="utf-8") as fh:
        tree = ast.parse(fh.read(), filename=path)
    content = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Dict):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name):
                try:
                    value = ast.literal_eval(node.value)
                except ValueError:
                    continue
                content.setdefault(normalize_category(target.id), {}).update(value)
    return content_to_entries(content)


def export_python_dicts(entries, path):
    content = entries_to_content(entries)
    lines = ["# -*- coding: utf-8 -*-",
             "# Generated by Multilingual Audio Studio", ""]
    for category, items in content.items():
        name = category + "s" if not category.endswith("s") else category
        clean = {i: {l: t for l, t in rec.items() if l in LANGUAGES} for i, rec in items.items()}
        lines.append(f"{name} = " + json.dumps(clean, ensure_ascii=False, indent=4))
        lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def read_csv_entries(path):
    entries = []
    with open(path, "r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        fields = [f.strip().lower() for f in (reader.fieldnames or [])]
        if "category" not in fields or "id" not in fields:
            raise ValueError("CSV needs at least 'category' and 'id' columns.")
        for row in reader:
            row = {str(k).strip().lower(): (v or "") for k, v in row.items() if k}
            entry = new_entry(normalize_category(row.get("category", "")), slugify(row.get("id", "")))
            if not entry["category"] or not entry["id"]:
                continue
            for key, text in row.items():
                lang = LANG_ALIASES.get(key, key)
                if lang in LANGUAGES:
                    entry[lang] = text.strip()
            entry["reviewed"] = row.get("reviewed", "").strip().lower() in ("1", "yes", "true", "y", "✔")
            entries.append(entry)
    return entries


def write_csv_entries(entries, path):
    # utf-8-sig so Excel shows Devanagari / Bengali / Gujarati correctly
    with open(path, "w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["category", "id"] + LANG_KEYS + ["reviewed"])
        for e in entries:
            writer.writerow([e["category"], e["id"]] + [e.get(l, "") for l in LANG_KEYS]
                            + ["yes" if e.get("reviewed") else "no"])
